target-version = "py311"
line-length = 79

[lint]
select = ["ALL"]

[lint.per-file-ignores]
# Unused import, missing docstr
"__init__.py" = ["F401", "D104"]
# Use of assert, missing docstr
"tests/*" = [
  "S101",  # Allow asserts in tests.
  "ANN001", "ANN101", "ANN201",  # No type annotations in tests.
  "D101", "D102", "D103",  # Missing docstr.
  "DTZ001",  # Allow time zone None.
  "SLF001", # Private member accessed - This is okay in test module.
  "INP001", # Do not enforce init file.
  ]

[lint.pycodestyle]
max-doc-length = 72

[lint.pydocstyle]
convention = "google"